export const regiones = [
  { id: 1, nombre: 'Amazonas' },
  { id: 2, nombre: 'Ancash' },
  { id: 3, nombre: 'Apurimac' },
  { id: 4, nombre: 'Arequipa' },
  { id: 5, nombre: 'Ayacucho' },
  { id: 6, nombre: 'Cajamarca' },
  { id: 7, nombre: 'Callao' },
  { id: 8, nombre: 'Cusco' },
  { id: 9, nombre: 'Huancavelica' },
  { id: 10, nombre: 'Huanuco' },
  { id: 11, nombre: 'Ica' },
  { id: 12, nombre: 'Junin' },
  { id: 13, nombre: 'La Libertad' },
  { id: 14, nombre: 'Lambayeque' },
  { id: 15, nombre: 'Lima' },
  { id: 16, nombre: 'Loreto' },
  { id: 17, nombre: 'Madre de Dios' },
  { id: 18, nombre: 'Moquegua' },
  { id: 19, nombre: 'Pasco' },
  { id: 20, nombre: 'Piura' },
  { id: 21, nombre: 'Puno' },
  { id: 22, nombre: 'San Martin' },
  { id: 23, nombre: 'Tacna' },
  { id: 24, nombre: 'Tumbes' },
  { id: 25, nombre: 'Ucayali' }
];